#!/usr/bin/env bash
# Bash script to install and configure haproxy on ubuntu server

# Update the apt
apt update

# install haproxy non-interactively
apt install haproxy -y

#start haproxy
service haproxy start

# append the configuration of frontend and backend to the configuration file
echo -e "
frontend http_fronthaul
	bind *:80
	default_backend http_backhaul

backend http_backhaul
	balance roundrobin
	server 176331-web-01 100.26.173.61 check
	server 176331-web-02 34.224.62.106 check" | tee -a /etc/haproxy/haproxy.cfg

# restart haproxy
service haproxy restart
