#!/usr/bin/env bash
# This script displays "Best School" 10 times and Hi on 9th iteration
str="Best School"
i=0
while [ $i -lt 10 ]
do
	echo "$str"
	((i++))
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
done
