#!/usr/bin/env bash
# This script displays "Best School" 10 times except bad luck on 4th iteration and good luck on 8th iteration
str="Best School"
i=0
while [ $i -lt 10 ]
do
	((i++))
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "$str"
	fi
done
